repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        language_version: python3
        exclude: ^tests/
        args:
        - -c 
        - bandit.conf
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black